AnimalShelter/Models/Animal.cs
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System;
using System.ComponentModel.DataAnnotations;



namespace AnimalShelter.Models
{
    public class Animal
    {
        public int AnimalId { get; set; }

        [DisplayName("Animal Type")]
        public string AnimalType { get; set; }

        [DisplayName("Animal Name")]
        public string AnimalName { get; set; }

        [DisplayName("Intake Date")]
        [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}")]
        public string IntakeDate { get; set; }

        // public void InputIntakeDate()
        // {
        //     DateTime dateInput = IntakeDate;
        //     // string parsedDate = dateInput.ToString("d", DateTimeFormatInfo.InvariantInfo);
        //     string parsedDate = dateInput.ToString("MM/dd/yyyy");
        //     IntakeDate = parsedDate;
        // }
    }

}
// ToLongDateString();
// (date1.ToString("d", DateTimeFormatInfo.InvariantInfo));

AnimalShelter/Models/AnimalShelterContext.cs
using Microsoft.EntityFrameworkCore;

namespace AnimalShelter.Models
{
    public class AnimalShelterContext : DbContext
    {
        public DbSet<Animal> Animals { get; set; }

        public AnimalShelterContext(DbContextOptions options) : base(options) { }
    }
}

AnimalShelter/Models/Shelter.cs
using System.Collections.Generic;

namespace AnimalShelter.Models
{
    public class Shelter
    {
        //public string getter and setters
    }
}

AnimalShelter/Controllers/AnimalsController.cs
using Microsoft.AspNetCore.Mvc;
using AnimalShelter.Models;
using System.Collections.Generic;
using System.Linq;

namespace AnimalShelter.Controllers
{
    public class AnimalsController : Controller
    {
        private readonly AnimalShelterContext _db;

        public AnimalsController(AnimalShelterContext db)
        {
            _db = db;
        }

        public ActionResult Index()
        {
            List<Animal> model = _db.Animals.OrderBy(animal => animal.IntakeDate).ToList();
            return View(model);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Animal animal)
        {
            // animal.InputIntakeDate();
            _db.Animals.Add(animal);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Details(int id)
        {
            Animal thisAnimal = _db.Animals.FirstOrDefault(animals => animals.AnimalId == id);
            return View(thisAnimal);
        }


    }
}

AnimalShelter/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using AnimalShelter.Models;
using System.Collections.Generic;

namespace AnimalShelter.Controllers
{
    public class HomeController : Controller
    {
        [HttpGet("/")]
        public ActionResult Index()
        {
            return View();
        }

    }
}

AnimalShelter/Controllers/SheltersController.cs
using System.Collections.Generic;
using System;
using Microsoft.AspNetCore.Mvc;
using AnimalShelter.Models;

namespace AnimalShelter.Controllers
{
    public class ShelterseController : Controller
    {
        // [HttpGet("/ParentObject")] //Display list of all ParentObjects
        // public ActionResult Index()
        // {
        // List<Category> allCategories = Category.GetAll(); //displaying all categories
        //     return View(allCategories);
        // }

        // [HttpGet("/ParentObject/new")] //user creates new ParentObject with form
        // public ActionResult New()
        // {
        //     return View();
        // }

        // [HttpPost("/ParentObject")] //Creates new ParentObject on server process form submission
        // public ActionResult Create(string categoryName) //accepts argument because it is referring to the contents in form 
        // {
        //     Category newCategory = new Category(categoryName); //create a new category
        //     return RedirectToAction("Index"); //sends the user back to the Index route
        // }

        // [HttpGet("/ParentObject/{id}")] //Display one specific ParentObject's details
        // public ActionResult Show(int id)
        // {
        //     Dictionary<string, object> model = new Dictionary<string, object>();
        //     Category selectedCategory = Category.Find(id);
        //     List<Item> categoryItems = selectedCategory.Items;
        //     model.Add("category", selectedCategory); //keys == "category" and "items"
        //     model.Add("items", categoryItems);
        //     return View(model); //view can only accept one model argument
        // }

    }
}

AnimalShelter/Views/Animals/Create.cshtml
@{
    Layout = "_Layout";
}

@model AnimalShelter.Models.Animal

<h4> Add a new animal</h4>
@using (Html.BeginForm())
{
    @Html.LabelFor(model => model.AnimalType)
    @Html.TextBoxFor(model => model.AnimalType)
    @Html.LabelFor(model => model.AnimalName)
    @Html.TextBoxFor(model => model.AnimalName)
    @Html.LabelFor(model => model.IntakeDate)
    @Html.TextBoxFor(model => model.IntakeDate, new { @type = "date"})
    <input type="submit" value="Add new animal" />
}

<p> @Html.ActionLink("Show all animals", "Index")</p>

AnimalShelter/Views/Animals/Details.cshtml
@{
    Layout = "_Layout";
}

@model AnimalShelter.Models.Animal

<h2>Animal Details</h2>
<hr />
<h3>@Html.DisplayNameFor(model => model.AnimalName): @Html.DisplayFor(model => model.AnimalName)</h3>
<h3>@Html.DisplayNameFor(model => model.AnimalType): @Html.DisplayFor(model => model.AnimalType)</h3>
<h3>@Html.DisplayNameFor(model => model.IntakeDate): @Html.DisplayFor(model => model.IntakeDate)</h3>
<p>@Html.ActionLink("Back to list", "Index")</p>

AnimalShelter/Views/Animals/Index.cshtml
@{
    Layout = "_Layout";
}
@using AnimalShelter.Models;
@model List<AnimalShelter.Models.Animal>;
@* @model AnimalShelter.Models.Animal; *@

<h1>Animals</h1>

@if (@Model.Count == 0)
{
    <h3>There's no animals in the shelter</h3>
}

<ul>
    @foreach (Animal animal in Model)
    {
        @* <h3>@Html.DisplayNameFor(model => model.AnimalType): @Html.DisplayFor(model => model.AnimalType)</h3> *@
        @* <li>@Html.DisplayNameFor($"{AnimalType}") : @Html.DisplayFor($"{animal.AnimalType}")</li> *@
        <li> @animal.AnimalType : @Html.ActionLink($"{animal.AnimalName}", "Details", new { id =
        animal.AnimalId}) <br> Intake Date: @animal.IntakeDate </li>
    }
</ul>

<p>@Html.ActionLink("Add a new animal", "Create")</p>


@* @Html.TextBoxFor(m => m.MyDate, new { Value = Model.MyDate.ToString("DD:MM:YYYY")}); *@

AnimalShelter/Views/Home/FavoritePhotos.cshtml
@*  <!DOCTYPE html>
    <html>

    <head>
    <title>WEBPAGE NAME</title>
    <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css'>
    </head>

    <body>
    <h1>Favorite Photos</h1>
    <ul>
    <li><img src='~/img/photo1.jpg' /></li>
    <li><img src='~/img/photo2.jpg' /></li>
    <li><img src='~/img/photo3.jpg' /></li>
    </ul>
    </body>

    </html>


    </html> *@

AnimalShelter/Views/Home/Index.cshtml
@{
    Layout = "_Layout";
}
<html>

<body>
    <h1>Welcome to Hamburger Helper's Animal Shelter</h1>
    <p>@Html.ActionLink("See all animals", "Index", "Animals")</p>

</body>

</html>

AnimalShelter/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Animal Shelter</title>
    <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css'>
    <link rel="stylesheet" href="~/css/styles.css">
</head>

<body>
    @RenderBody()

</body>

</html>